config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'admin/freights#index'









  post 'admin/transations/report' => 'admin/transations#report',
       :as => :admin_transation_report


  post 'admin/transations/get_report' => 'admin/transations#get_report',
       :as => :transation_reports

  get  'admin/motorists/paid_motorist' => 'admin/motorists#paid_motorist',
        :as => :admin_motorist_paid

  post  'admin/motorists/paid_motorist_step_2' => 'admin/motorists#paid_motorist_step_2',
       :as => :admin_motorist_paid_step_2

get  'admin/motorists/valley_motorist' => 'admin/motorists#valley_motorist',
        :as => :admin_motorist_valley

  post  'admin/motorists/valley_motorist_step_2' => 'admin/motorists#valley_motorist_step_2',
       :as => :admin_motorist_valley_step_2

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/client.rb
class Client  < ActiveRecord::Base

  self.table_name = "People"

  default_scope { where(type_person: '2') }

  before_create :set_type_person

  has_many :freights, :class_name => "Freight", :foreign_key => "clientId"

  accepts_nested_attributes_for :freights

  attr_accessible :name, :cpf, :type_person, :freights, :phone

  validates :name, :presence => true

  validates :cpf, cpf: true, :allow_blank => true

  validates :cpf, :uniqueness => { :allow_blank => true}

  def set_type_person
    self.type_person = 2
  end
end

app/models/freight.rb
class Freight < ActiveRecord::Base

  belongs_to :truck, class_name: "Truck", foreign_key: "truckId"
  belongs_to :motorist, class_name: "Motorist", foreign_key: "motoristId"
  belongs_to :client, class_name: "Client", foreign_key: "clientId"

  attr_accessible :truckId, :truck, :motorist, :motoristId, :client, :clientId, :origin,
      :destination, :valueKm, :distanceKm, :description, :situation, :spent, :descriptionSpent,
      :numberHead, :exitDate, :arrivalDate, :paidDriver, :receipt_date, :client_attributes

  accepts_nested_attributes_for :client

  scope :by_motorist, lambda{|motorist_id| where("motoristId = ?", motorist_id)}

  scope :by_paid, lambda{|paid| where("paidDriver = ?", paid)}

  validates :truckId, :motoristId, :clientId, :valueKm, :distanceKm, :origin, :destination, :situation,
            :exitDate, :arrivalDate, :presence => true

  validates :spent, :numericality => { :greater_than_or_equal_to => 0 }


end

app/models/motorist.rb
class Motorist < ActiveRecord::Base

  self.table_name = "People"

  default_scope { where(type_person: '1') }

  before_create :set_type_person

  has_many :freights, :class_name => "Freight", :foreign_key => "motoristId"

  has_many :paid_motorists, :class_name => "PaidMotorist", :foreign_key => "motoristId", :dependent => :destroy

  has_many :valleys, :class_name => "Valley", :foreign_key => "motoristId", :dependent => :destroy

  accepts_nested_attributes_for :freights, :paid_motorists

  attr_accessor :percentage, :salary, :total, :value_total_freight, :truckId, :total_valley

  attr_accessible :name, :cpf, :type_person, :freights, :paid_motorists, :valleys, :phone, :salary,
   :percentage, :total, :value_total_freight, :total_valley

  validates :name, :presence => true

  validates :cpf, cpf: true, :allow_blank => true

  validates :cpf, :uniqueness => { :allow_blank => true}

  def set_type_person
    self.type_person = 1
  end

end

app/models/paid_motorist.rb
class PaidMotorist < ActiveRecord::Base

  belongs_to :truck, :class_name => "Truck", :foreign_key => "truckId"

  belongs_to :motorist, :class_name => "Motorist", :foreign_key => "motoristId"

  attr_accessible :description, :value, :date,  :truck, :truckId, :motorist, :motoristId

  accepts_nested_attributes_for :truck, :motorist

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name, :cpf, :type_person, :phone
end

app/models/spent.rb
class Spent < ActiveRecord::Base

	belongs_to :truck, :class_name => "Truck", :foreign_key => "truck_id"

	attr_accessible :date_spent, :description, :value, :truck, :truck_id, :id

	validates :truck_id, :date_spent, :value, :presence => true

end

app/models/transation.rb
class Transation < ActiveRecord::Base

  belongs_to :truck, :class_name => "Truck", :foreign_key => "truckId"

  belongs_to :motorist, :class_name => "Motorist", :foreign_key => "motoristId"

  attr_accessor :start_date, :end_date, :truck_chosen

  attr_accessible :objectName, :objectId, :description, :value, :dateTransation,  :truck, :truckId, :motorist, :motoristId,:truck_chosen,  :start_date, :end_date, :type_transation

  accepts_nested_attributes_for :truck, :motorist

end

app/models/truck.rb
class Truck < ActiveRecord::Base

  has_many :freights, :class_name => "Freight", :foreign_key => "truckId"

  accepts_nested_attributes_for :freights

  attr_accessible :board, :year, :axes, :freights, :truckId

  validates :board, :presence => true

end

app/models/valley.rb
class Valley < ActiveRecord::Base

  belongs_to :motorist, :class_name => "Motorist", :foreign_key => "motoristId"

  attr_accessible :description, :value, :date, :status, :created_at, :updated_at, :motorist, :motoristId

  accepts_nested_attributes_for :motorist

  validates :value, :date, :motoristId, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
# encoding: UTF-8
module DateHelper

	def self.valid_date?(str)
    !!(str=~ /[0-9]{4}-[0-9]{2}-[0-9]{2}/)
  end

  def self.str_to_date(date)
    Date.strptime(date,"%Y-%m-%d")
  end

  def self.str_to_date2(date)
    Date.strptime(date, "%m/%d/%Y")
  end

  def self.format_date2(date)

  end

  def self.format_date(date, format = "%d/%m/%Y")
    if date && date.class == String && !date.empty?
      self.format_date(Date.parse(date), format)
    else
  	  date.strftime(format) if date && date.class != String
    end
  end

  def self.format_date_time(datetime, format = "%d/%m/%Y - %H:%M:%S")
    if datetime && datetime.class == String && !datetime.empty?
      self.format_date_time(DateTime.parse(datetime), format)
    else
      datetime.strftime(format) if datetime && datetime.class != String
    end
  end

  def self.format_oas_date(date)
  	self.format_date date, "%Y-%m-%d"
  end

  def self.format_en_date(time)
    time.strftime("%Y-%m-%d")
  end

  def self.format_date_without_separator(date)
    date.strftime("%Y%m%d")
  end

  def self.date_overlaps?(start_date_period, end_date_period, date_compare)
    (start_date_period - date_compare) * (date_compare - end_date_period) >= 0
  end

  def self.dates_overlaps?(start_date_initial, end_date_initial, start_date_final, end_date_final)
    (start_date_initial - end_date_final) * (start_date_final - end_date_initial) >= 0
  end

  def self.date_to_string

  end

  def self.day_of_week(date)
    days = ["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"]
    days[(date.wday)]
  end

end

app/helpers/status_helper.rb
# encoding: UTF-8
module StatusHelper

  SITUATION = {
      0 => "A receber",
      1 => "Recebido"
  }

  SITUATION_OPTIONS = [
      OpenStruct.new( :id => 0, :name => 'A receber'),
      OpenStruct.new( :id => 1, :name => 'Recebido')
  ]

  PAID_DRIVER = {
      0 => "Não",
      1 => "sim",
      nil => "Não",
      false => "Não",
      true => "Sim"
  }
end

app/views/admin/clients/_form.html.erb
<%= semantic_form_for [:admin, @client] do |f| %>

    <%= f.inputs do %>
        <%= f.input :name, input_html: { class: "campo20" } %>
        <%= f.input :cpf, input_html: { class: "cpf campo10" } %>
        <%= f.input :phone, input_html: { class: "phone campo10" } %>
    <% end %>
    <%= f.actions %>

    <% if @client.present? %>

        <div class="div-separar clear-both">&nbsp;</div>

        <table class="index_table">
          <thead>
          <tr>
            <th>Saida</th>
            <th>Destino</th>
            <th>Data de saida</th>
            <th>Data de chegada</th>
            <th>Situação</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <%  @client.freights.each do |freight| %>
              <tr>
                <td><%= freight.origin %></td>
                <td><%= freight.destination %></td>
                <td><%= DateHelper.format_date(freight.exitDate) %></td>
                <td><%= DateHelper.format_date(freight.arrivalDate) %></td>
                <td><%= StatusHelper::SITUATION[freight.situation] %> </td>
                <td><%= link_to "editar", edit_admin_freight_path(freight) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>

    <% end %>

<% end %>

app/views/admin/freights/_form.html.erb
<%= semantic_form_for [:admin, @freight] do |f| %>

      <%= f.inputs do %>
          <%= f.input :motorist, :as => :select, :collection => Motorist.where(:type_person => 1)%>
          <%= f.input :client, :as => :select, :collection => Client.where(:type_person => 2) %>
          <%= f.input :truck, :as => :select, :collection => Truck.all.map{|b| [b.board,b.id]} %>
          <%= f.input :origin, input_html: { class: "campo20" } %>
          <%= f.input :destination, input_html: { class: "campo20" } %>
          <%= f.input :valueKm, as: :string, input_html: { onkeypress: "return isFloatKey(this,event)", class: "campo20" } %>
          <%= f.input :distanceKm, as: :string, input_html: { onkeypress: "return isFloatKey(this,event)", class: "campo20"  } %>
          <%= f.input :description, as: :text, input_html: { class: "campo20", rows: 5,
                                                             onkeyup: "maxLengthText(this);", maxlength: "1000" }, :hint=> "<span id=\"contador\"></span>".html_safe %>
          <%= f.input :situation,  :as => :select, :collection => StatusHelper::SITUATION_OPTIONS %>
          <%= f.input :receipt_date, :as => :string, :input_html => {class: "campo10 input_date_picker", value: DateHelper.format_date(f.object.receipt_date)}  %>
          <%= f.input :spent, input_html: { class: "campo20" } %>
          <%= f.input :descriptionSpent, input_html: { class: "campo20", rows: 5,
                                                       onkeyup: "maxLengthText(this);", maxlength: "1000" }, :hint=> "<span id=\"contador\"></span>".html_safe %>
          <%= f.input :numberHead, input_html: { class: "campo20" } %>
          <%= f.input :exitDate, :as => :string, :input_html => {class: "campo10 input_date_picker", value: DateHelper.format_date(f.object.exitDate)}  %>
          <%= f.input :arrivalDate, :as => :string, :input_html => {class: "campo10 input_date_picker", value: DateHelper.format_date(f.object.arrivalDate)}  %>
      <% end %>
    <%= f.actions %>
<% end %>

app/views/admin/motorists/_form.html.erb
<%= semantic_form_for [:admin, @motorist] do |f| %>

    <%= f.inputs do %>
        <%= f.input :name, input_html: { class: "campo20" } %>
        <%= f.input :cpf, input_html: { class: "cpf campo10" } %>
        <%= f.input :phone, input_html: { class: "phone campo10" } %>
    <% end %>
    <%= f.actions %>

    <% if @motorist.paid_motorists.present? %>

        <div class="div-separar clear-both">&nbsp;</div>

        <h3> Pagamentos</h3>

        <table class="index_table">
          <thead>
          <tr>
            <th>Data</th>
            <th>Valor</th>
          </tr>
          </thead>
          <tbody>
          <% @motorist.paid_motorists.order(date: :desc).each do |f|%>
              <tr>
                <td><%= DateHelper.format_date(f.date) %></td>
                <td><%= f.value %></td>
              </tr>
          <%end%>
          </tbody>
        </table>
    <%end%>

    <% if @motorist.valleys.where(:status=>false).present? %>
        
        <h3>Vales</h3>
        <table class="index_table">
          <thead>
          <tr>
            <th>Data</th>
            <th>Valor</th>
            <th>Descrição</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <%  @motorist.valleys.where(:status=>false).each do |valley| %>
              <tr>
                <td><%= DateHelper.format_date(valley.date) %></td>
                <td><%= valley.value %></td>
                <td><%= valley.description %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
    <%end%>
         <br>
    <% if @motorist.present? %>
        <h3>Fretes</h3>
        <table class="index_table">
          <thead>
          <tr>
            <th>Saida</th>
            <th>Destino</th>
            <th>Data de saida</th>
            <th>Data de chegada</th>
            <th>Motorista pago</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <%  @motorist.freights.each do |freight| %>
              <tr>
                <td><%= freight.origin %></td>
                <td><%= freight.destination %></td>
                <td><%= DateHelper.format_date(freight.exitDate) %></td>
                <td><%= DateHelper.format_date(freight.arrivalDate) %></td>
                <td><%= StatusHelper::PAID_DRIVER[freight.paidDriver] %></td>
                <td><%= link_to "editar", edit_admin_freight_path(freight) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>

    <% end %>
<% end %>

app/views/admin/motorists/paid_motorist.html.erb
<%= semantic_form_for @motorist, :url => admin_motorist_paid_step_2_path, :method => :post,
                      :html => { :target => :_blank } do |f| %>
    <%= f.inputs do %>
        <%= f.input :truckId, :as => :select, :collection => Truck.all.map{|b| [b.board,b.id]} %>
        <%= f.input :id, input_html: { class: 'campo10', value: @motorist.id },  as: :hidden %>
        <%= f.input :salary, input_html: { class: 'campo10' } %>
        <%= f.input :percentage, :input_html => {class: "campo10"} %>
        <%= f.input :value_total_freight, :input_html => { class: "input-non-edit campo10", :readonly => true, value: @value_total } %>
        <%= f.input :total, :input_html => { class: "input-non-edit campo10", :readonly => true} %>
        <%= f.input :total_valley, :input_html => { class: "input-non-edit campo10", :readonly => true, value: @total_valley } %>
        <%= f.actions do %>
            <%= f.action :submit, :label => I18n.t('button.paid_confirm') %>
        <% end %>
    <% end %>

  <% if @motorist.valleys.where(:status=>false).present? %>
    <h3>Vales</h3>
    <table class="index_table">
      <thead>
      <tr>
        <th>Data</th>
        <th>Valor</th>
        <th>Descrição</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <%  @motorist.valleys.where(:status=>false).each do |valley| %>
          <tr>
            <td><%= DateHelper.format_date(valley.date) %></td>
            <td><%= valley.value %></td>
            <td><%= valley.description %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>
    <%end%>
     

    <h3>Fretes</h3>
    <table class="index_table">
      <thead>
      
      <tr>
        <th>Cliente</th>
        <th>Origem</th>
        <th>Destino</th>
        <th>Data de Saida</th>
        <th>Data de Chegada</th>
        <th>Valor do frete</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @freights.each do |freight| %>
          <tr>
            <td><%= link_to freight.client.name, edit_admin_client_path(freight.client) %></td>
            <td><%= freight.origin %></td>
            <td><%= freight.destination %></td>
            <td><%= DateHelper.format_date(freight.exitDate) %></td>
            <td><%= DateHelper.format_date(freight.arrivalDate) %></td>
            <td><%= (freight.valueKm * freight.distanceKm) %></td>
            <td><%= link_to "editar", edit_admin_freight_path(freight.id) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

app/views/admin/motorists/valley_motorist.html.erb
<%= semantic_form_for @valley, :url => admin_motorist_valley_step_2_path, :method => :post,
                      :html => { :target => :_blank } do |f| %>

      <%= f.inputs do %>
          <%= f.input :motorist, :as => :select, :collection => Motorist.where(:type_person => 1)%>
          <%= f.input :value, input_html: { class: "campo10" } %>
          <%= f.input :date, :as => :string, :input_html => {class: "campo10 input_date_picker", value: DateHelper.format_date(f.object.date)}  %>
          <%= f.input :description, as: :text, input_html: { class: "campo20", rows: 5,
                                                   onkeyup: "maxLengthText(this);", maxlength: "1000" }, :hint=> "<span id=\"contador\"></span>".html_safe %>
      <% end %>
    <%= f.actions do %>
            <%= f.action :submit, :label => I18n.t('button.valley_confirm') %>
    <% end %>
<% end %>

app/views/admin/spents/_form.html.erb
<%= semantic_form_for [:admin, @spent] do |f| %>

    <%= f.inputs do %>
  		<%= f.input :truck, :as => :select, :collection => Truck.all.map{|b| [b.board,b.id]}, input_html: { class: "campo10"} %>
        <%= f.input :value, input_html: { class: "campo10 money", :"data-thousands" => "", :"data-decimal" => ".", :"data-prefix" => ""}  %>
        <%= f.input :description, as: :text, input_html: { class: "campo20", rows: 5,
                                                           onkeyup: "maxLengthText(this);", maxlength: "1000" }, :hint=> "<span id=\"contador\"></span>".html_safe %>
        <%= f.input :date_spent, :as => :string, :input_html => {class: "campo10 input_date_picker", value: DateHelper.format_date(f.object.date_spent) }  %>	
    <% end %>
<%= f.actions %>
<% end %>

app/views/admin/transations/_form.html.erb
<%= semantic_form_for [:admin, @transation] do |f| %>

    <%= f.inputs do %>
        <%= f.input :truck, :as => :select, :collection => Truck.all.map{|b| [b.board,b.id]} %>
        <%= f.input :value, input_html: { class: "campo10 money", :"data-thousands" => "", :"data-decimal" => ".", :"data-prefix" => "" }  %>
        <%= f.input :description, as: :text, input_html: { class: "campo20", rows: 5,
                                                           onkeyup: "maxLengthText(this);", maxlength: "1000" }, :hint=> "<span id=\"contador\"></span>".html_safe %>
    <% end %>
<%= f.actions %>
<% end %>

app/views/admin/transations/index.html.erb
<%= semantic_form_for @transation, :url => transation_reports_path, :method => :post,
                      :html => { :target => :_blank } do |f| %>
    <%= f.inputs do %>
    	<%= f.input :truck_chosen, :as => :select, :collection => Truck.all.map{|b| [b.board,b.id]} %>
        <%= f.input :start_date, :as => :string, :input_html => {class: "campo10 input_date_picker", value: DateHelper.format_date(f.object.start_date)}, :label => 'Data início' %>
        <%= f.input :end_date, :as => :string, :input_html => {class: "campo10 input_date_picker", value: DateHelper.format_date(f.object.end_date)}, :label => 'Data fim' %>

        <%= f.actions do %>
            <%= f.action :submit, :label => I18n.t('button.run_report') %>
        <% end %>
    <% end %>
<% end %>

app/views/admin/transations/report.html.erb
<br clear="all">
<h3>Fretes - saídas</h3>
<table class="index_table campo70">

  <thead>
  <tr>
    <th>Data de chegada</th>
    <th>caminhão</th>
    <th>Descrição</th>
    <th>Valor</th>
    <th>Referente ao</th>
  </tr>
  </thead>

  <tbody>
    <% if @freights_spent.present? %>
      <% @freights_spent.each do |freight| %>
          <% client_name = freight.client.name if freight.client.present? %>
          <tr>
            <td><%= (DateHelper.format_date(freight["arrivalDate"])) %></td>
            <td><%= freight.truck.board if freight.truck.present? %></td>
            <td><%= freight["description"] %></td>
            <td><%= freight["spent"] %></td>
            <td><%= link_to "frete de #{freight["origin"]} - #{freight["destination"]}, #{client_name}", edit_admin_freight_path(freight["id"]) %></td>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h3>Fretes - entradas</h3>
<table class="index_table campo70">

  <thead>
  <tr>
    <th>Data de chegada</th>
    <th>Data do recebimento </th>
    <th>caminhão</th>
    <th>Descrição</th>
    <th>Valor</th>
    <th>Referente ao</th>
  </tr>
  </thead>

  <tbody>
  <% if @freights_receipt.present? %>
      <% @freights_receipt.each do |freight| %>
            <% client_name = freight.client.name if freight.client.present? %> 
          <tr>
            <td><%= (DateHelper.format_date(freight["arrivalDate"])) %></td>
            <td><%= (DateHelper.format_date(freight["receipt_date"])) %></td>
            <td><%= freight.truck.board if freight.truck.present? %></td>
            <td><%= freight["description"] %></td>
            <td><%= freight["valueKm"]*freight["distanceKm"] %></td>
            <td><%= link_to "frete de #{freight["origin"]} - #{freight["destination"]}, #{client_name}", edit_admin_freight_path(freight["id"]) %></td>
            <% @freights_receipt_total += freight["valueKm"]*freight["distanceKm"] %>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

<h3>Resumo dos fretes</h3>
<table class="index_table campo70">
  <thead>
  <tr>
    <th>Entrada</th>
    <th>Saida</th>
    <th>Liquido</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @freights_receipt_total %></td>
    <td><%= @freights_spent_total %></td>
    <td><%= @freights_receipt_total - @freights_spent_total  %></td>
  </tr>
  </tbody>

</table>

<h3>Gastos com caminhões</h3>
<table class="index_table campo70">

  <thead>
  <tr>
    <th>Data</th>
    <th>caminhão</th>
    <th>Descrição</th>
    <th>Valor</th>
    <th>Referente ao</th>
  </tr>
  </thead>

  <tbody>
  <% if @spents.present? %>
      <% @spents.each do |spent| %>
          <tr>
            <td><%= (DateHelper.format_date(spent["date_spent"])) %></td>
            <td><%= spent.truck.board if spent.truck.present? %></td>
            <td><%= spent["description"] %></td>
            <td><%= spent["value"]%></td>
            <td><%= link_to "Gasto de identificador #{spent["id"]}", edit_admin_spent_path(spent["id"]) %></td>
          </tr>
      <% end %>
      <tr>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%= "total dos gastos" %></td>
        <td><%= @spent_total %></td>
        <td><%=  %></td>
      </tr>
  <% end %>
  </tbody>
</table>


app/views/admin/trucks/_form.html.erb
<%= semantic_form_for [:admin, @truck] do |f| %>

    <%= f.inputs do %>
        <%= f.input :board, input_html: { class: "campo20" } %>
        <%= f.input :year, as: :string, input_html: { onkeypress: "return isIntegerKey(this,event)", class: "campo20" } %>
    <% end %>
    <%= f.actions %>

    <% if @truck.present? %>

        <div class="div-separar clear-both">&nbsp;</div>

        <table class="index_table">
          <thead>
          <tr>
            <th>Saida</th>
            <th>Destino</th>
            <th>Data de saida</th>
            <th>Data de chegada</th>
            <th>Quantidade de KM</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <%  @truck.freights.each do |freight| %>
              <tr>
                <td><%= freight.origin %></td>
                <td><%= freight.destination %></td>
                <td><%= DateHelper.format_date(freight.exitDate) %></td>
                <td><%= DateHelper.format_date(freight.arrivalDate) %></td>
                <td><%= freight.distanceKm %></td>
                <td><% link_to "edit", edit_admin_freight_path(freight) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>

    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FreteAdm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>